### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by theNestruo** [einar-saukas/ZX0#2]
Hi, Einar Saukas!

Not an actual issue, but a suggestion. Could you tag/release the project here in github? It will make easier for us to know if there has been changes (I can "watch" releases, but not particular commits), and it will be easier to keep the versions of zx0.exe and the decompressor routine matching.

Thank you very much!

Edit: Actually, it seems I can "watch" all activity in the repository, but I still think tagging/releasing new versions would be a great idea!

**Comment by einar-saukas** [comment]
Hi Néstor,

No problem! I just want to try to reduce the "mega" decompressor size first, afterwards I will generate an official tag for current release version 1.2.

In the meantime, you can simply click on "watch" to get informed of any changes.
