### ISSUE TITLE
[question] any plan for 6502 depacker routines ?

### ISSUE THREAD

**Issue by shazz** [einar-saukas/ZX0#3]
I may give it a try but I doubt I will be able to code something as efficient. So maybe you're already have it in mind?

**Comment by einar-saukas** [comment]
Hi shazz,

I have no plans for other ports myself, but they are welcome.

A few people had provided different ports of ZX7 to 6502 in the past. You may want to contact them, I'm sure one of them will be interested to port ZX0 too.
