### ISSUE TITLE
[question] dependencies to Watcom compiler?

### ISSUE THREAD

**Issue by shazz** [einar-saukas/ZX0#4]
Hi, I tried to compile the compressor with Watcom for Linux but it looks like Watcom binaries are really outdated and it crashed. Before trying with gcc, any dependencies with watcom to be replaced?

**Comment by einar-saukas** [comment]
Hi shazz,

These are no dependencies. It's just standard C using standard libraries, so it will work on any compiler.

Even so, the compiler choice makes a huge difference in performance. In my preliminary tests under Windows, the ZX0 compressor executed in 12 minutes when compiled with Visual Studio, 2 minutes when compiled with gcc, 9 seconds when compiled with Open Watcom. The compressor execution is almost pure processing, with minimal I/O and O.S. interaction, therefore it all depends on the code generated by the compiler. I made further changes to the compressor afterwards, so these numbers are not accurate anymore, but they shouldn't have changed too much.

A different O.S. may also provide different results. I suggest you try both Watcom and gcc under Linux to compare. The compiler settings also make a lot of difference, you better check them too. The Makefile I provided here contains the fastest settings I got for Open Watcom, unfortunately I don't have the fastest settings for gcc anymore.
