### ISSUE TITLE
Crashing when using prefix mode

### ISSUE THREAD

**Issue by specke** [einar-saukas/ZX0#5]
I am experincing crashes when trying to compress files containing a common prefix.
For each file in the attached zip, the latest version of ZX0 (ver.1.4 at the moment) crashes when trying to invoke it with the command line
zx0.exe +256 example1.bin
or
zx0.exe +256 example2.bin
[crash256.zip](https://github.com/einar-saukas/ZX0/files/5936352/crash256.zip)

**Comment by einar-saukas** [comment]
Hi introspec,

There was a bug in compression with prefix. My apologies!

It's fixed now. Thank you for reporting it!
